fix: Calculate link `t_size`s correctly (#388)
This PR contains a few minor fixes and refactors, but mainly this fixes
a bad `t_size` calculation. We ended up setting the `t_size` of a link
to the size of the *node* it points to, when in fact it should be the
entire *DAG* it points to, cumulatively up to the root.

We also had a bad calculation in the check, which this also addresses.


#### PR Dependency Tree


* **PR #388** 👈

This tree was auto-generated by
[Charcoal](https://github.com/danerwilliams/charcoal)

---------

Co-authored-by: ash <alan@storacha.network>

diff --git a/test/doupload b/test/doupload
--- a/test/doupload
+++ b/test/doupload
@@ -104,22 +104,15 @@ exec 3>&1
 
 sandbox="doupload-dir"
 
-export GUPPY_REPO_DATA_DIR=./$sandbox/storacha 
-
-# Configure guppy
-if [[ -n "$database_url" ]]; then
-	export GUPPY_REPO_DATABASE_URL="$database_url"
-fi
+go build -gcflags="all=-N -l" .. || { echo "Failed to build guppy"; exit 1; }
 
 export STORACHA_SERVICE_URL="https://staging.up.warm.storacha.network"
 export STORACHA_SERVICE_DID="did:web:staging.up.warm.storacha.network"
 export STORACHA_RECEIPTS_URL="https://staging.up.warm.storacha.network/receipt/"
 export STORACHA_INDEXING_SERVICE_URL="https://staging.indexer.warm.storacha.network"
 export STORACHA_INDEXING_SERVICE_DID="did:web:staging.indexer.warm.storacha.network"
-
-guppy() {
-	go run .. "$@"
-}
+export GUPPY_REPO_DATA_DIR="./$sandbox/storacha"
+export GUPPY_REPO_DATABASE_URL="$database_url"
 
 dataDir="$sandbox/data"
 outDir1="$sandbox/out1"
@@ -190,29 +183,39 @@ main () {
 
 	echo
 	echo "🎁 Generating new space"
-	space=$(guppy space generate | tee /dev/fd/3)
+	space=$(./guppy space generate | tee /dev/fd/3)
 
 	echo
 	echo "📜 Listing space info"
-	guppy space info "$space"
+	./guppy space info "$space"
 
 	echo
 	echo "📤 Uploading data from $dataDir to space $space"
-	guppy upload source add "$space" "$dataDir"
-	rootCID=$(guppy upload "$space" | tee /dev/fd/3 | grep 'Upload completed successfully:' | awk '{print $4}')
+	./guppy upload source add "$space" "$dataDir"
+	rootCID=$(./guppy upload "$space" | tee /dev/fd/3 | grep 'Upload completed successfully:' | awk '{print $4}')
+
+	echo
+	echo "🧐 Checking local upload state"
+	./guppy upload check "$space"
+	echo "✅ Upload state passed checks!"
+
+	echo
+	echo "🕵 Verifying uploaded data is accessible and consistent"
+	./guppy verify "$rootCID"
+	echo "✅ Uploaded data verified!"
 
 	echo
 	echo "📥 Retrieving data from space $space with root CID $rootCID to $outDir1"
-	guppy retrieve "$space" "$rootCID" "$outDir1"
+	./guppy retrieve "$space" "$rootCID" "$outDir1"
 
 	echo
 	echo "📥 Retrieving data from only subdir with root CID $rootCID to $outDir2"
-	guppy retrieve "$space" "$rootCID/small-files" "$outDir2"
+	./guppy retrieve "$space" "$rootCID/small-files" "$outDir2"
 
 
 	echo
 	echo "🔄 Resetting client"
-	guppy reset
+	./guppy reset
 	echo "🔐 Logging in as $account again"
 
 	# Log in again
@@ -223,13 +226,13 @@ main () {
 
 	echo
 	echo "📥 Retrieving data from space $space with root CID $rootCID to $outDir3"
-	guppy retrieve "$space" "$rootCID" "$outDir3"
+	./guppy retrieve "$space" "$rootCID" "$outDir3"
 
 	echo "↔️ Verifying retrieved data matches original"
 	diff -r "$dataDir" "$outDir1"
 	diff -r "$dataDir/small-files" "$outDir2"
 	diff -r "$dataDir" "$outDir3"
-	echo "✅ Data verified!"
+	echo "✅ Retrieval verified!"
 
 	jq -n \
 		--arg account "$account" \
@@ -243,7 +246,7 @@ main () {
 log_in() {
 	local account="$1"
 	# Start login in background
-	guppy login "$account" >/dev/null &
+	./guppy login "$account" >/dev/null &
 	login_pid=$!
 	cleanup_pids+=("$login_pid")
 
