refactor: Handle TLS in a separate nginx process

diff --git a/test/gatewayretrieve b/test/gatewayretrieve
--- a/test/gatewayretrieve
+++ b/test/gatewayretrieve
@@ -14,6 +14,10 @@ if ! command -v jq &> /dev/null; then
 		echo "jq could not be found, please install it to run this script."
 		exit 1
 fi
+if ! command -v nginx &> /dev/null; then
+		echo "nginx could not be found, please install it to run this script."
+		exit 1
+fi
 if ! command -v ipfs &> /dev/null; then
 		echo "ipfs (Kubo) could not be found, please install it to run this script."
 		exit 1
@@ -46,16 +50,33 @@ fi
 
 mprocsPort=4050
 gupwayPort=3000
-gupwayRoutingPort=3001
+gupwayTlsPort=3443
+kuboApiPort=5001
+
+scriptsDir="$(cd ../scripts && pwd)"
 
 rm -rf "$IPFS_PATH"
 ipfs init
+ipfs config --json Addresses "$(jq -n \
+	--arg kuboApiPort "$kuboApiPort" \
+	'{
+    "API": "/ip4/127.0.0.1/tcp/\($kuboApiPort)",
+    "Gateway": [],
+    "Swarm": [],
+    "Announce": [],
+    "NoAnnounce": [],
+    "AppendAnnounce": []
+  }'
+)"
 ipfs config --json Routing "$(jq -n \
-	--arg gupwayRoutingPort "$gupwayRoutingPort" \
-	'{"Type": "delegated", "DelegatedRouters": ["http://localhost:\($gupwayRoutingPort)"]}'
+	--arg gupwayPort "$gupwayPort" \
+	'{"Type": "delegated", "DelegatedRouters": ["http://localhost:\($gupwayPort)"]}'
 )"
 ipfs config --bool Provide.Enabled false
+ipfs config --bool AutoTLS.Enabled false
 ipfs config --bool HTTPRetrieval.TLSInsecureSkipVerify true
+ipfs config Plugins.Plugins.telemetry.Config.Mode off
+ipfs config --bool Discovery.MDNS.Enabled false
 
 openssl req -x509 -newkey rsa:2048 -keyout "$keyFile" -out "$certFile" \
   -days 36500 -nodes -subj "/CN=localhost" \
@@ -69,9 +90,10 @@ jq -n \
 	--arg mprocsServer "127.0.0.1:$mprocsPort" \
 	--arg guppy "${guppy[*]}" \
 	--arg gupwayPort "$gupwayPort" \
+	--arg gupwayTlsPort "$gupwayTlsPort" \
 	--arg certFile "$certFile" \
 	--arg keyFile "$keyFile" \
-	--arg gupwayRoutingPort "$gupwayRoutingPort" \
+	--arg scriptsDir "$scriptsDir" \
 	--arg space "$space" \
 	--arg rootCID "$rootCID" \
 	--arg outDir "$outDir" \
@@ -79,13 +101,20 @@ jq -n \
 		server: "\($mprocsServer)",
 		procs: {
 			gupway: {
-				shell: "\($guppy) gateway serve --port=\($gupwayPort) --trusted=false --tls-cert=\($certFile) --tls-key=\($keyFile) --routing-port=\($gupwayRoutingPort) \($space)"
+				shell: "\($guppy) gateway serve --log-level=info --port=\($gupwayPort) --tls-port=\($gupwayTlsPort) --trusted=false \($space)"
+			},
+			"nginx-tls": {
+				shell: "sleep 1 && mprocs --server \"\($mprocsServer)\" --ctl \"{c: select-proc, index: 1}\" && \($scriptsDir)/nginx-tls-proxy.sh --cert \($certFile) --key \($keyFile) --listen \($gupwayTlsPort) --upstream \($gupwayPort)",
+				stop: "SIGTERM"
 			},
 			"kubo-daemon": {
-				shell: "sleep 2 && echo $SSL_CERT_FILE && mprocs --server \"\($mprocsServer)\" --ctl \"{c: select-proc, index: 1}\" && ipfs daemon"
+				shell: "sleep 2 && mprocs --server \"\($mprocsServer)\" --ctl \"{c: select-proc, index: 2}\" && ipfs daemon"
+			},
+			"kubo-daemon-logging": {
+				shell: "sleep 3 && ipfs log level bitswap/session info"
 			},
 			"kubo-get": {
-				shell: "sleep 4 && mprocs --server \"\($mprocsServer)\" --ctl \"{c: select-proc, index: 2}\" && echo \"Getting /ipfs/\($rootCID)\" && ipfs get /ipfs/\($rootCID) -o \($outDir) && mprocs --server \"\($mprocsServer)\" --ctl \"{c: quit}\""
+				shell: "sleep 4 && mprocs --server \"\($mprocsServer)\" --ctl \"{c: select-proc, index: 4}\" && echo \"Getting /ipfs/\($rootCID)\" && GOLOG_LOG_LEVEL=info ipfs get /ipfs/\($rootCID) -o \($outDir) && mprocs --server \"\($mprocsServer)\" --ctl \"{c: quit}\""
 			}
 		},
 	}' > "$config"
